# Generated by Django 6.0.6 on 2026-06-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
