# Generated by Django 6.0.6 on 2026-06-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='advance_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
