# Generated by Django 6.0.6 on 2026-06-29 13:14

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_advance_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_date',
            field=models.DateField(default=orders.models.default_pickup_date),
        ),
    ]
